package ywcai.ls.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "mrapp")
public class Product {

	
	private Integer uid;
	private int productid;
	private int packcode;
	private int flowsize;
	private int price;
	private int rate;
	private int local;
	private String operator;
	private String province;
	private String des;
	private int delflag;

//	public Product() {
//	}

//	public Product(int productid, int packcode, int flowsize, int price, int rate, int local, String operator,
//			int delflag) {
//		this.productid = productid;
//		this.packcode = packcode;
//		this.flowsize = flowsize;
//		this.price = price;
//		this.rate = rate;
//		this.local = local;
//		this.operator = operator;
//		this.delflag = delflag;
//	}

//	public Product(int productid, int packcode, int flowsize, int price, int rate, int local, String operator,
//			String province, String des, int delflag) {
//		this.productid = productid;
//		this.packcode = packcode;
//		this.flowsize = flowsize;
//		this.price = price;
//		this.rate = rate;
//		this.local = local;
//		this.operator = operator;
//		this.province = province;
//		this.des = des;
//		this.delflag = delflag;
//	}

	@Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "productid", nullable = false)
	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	@Column(name = "packcode", nullable = false)
	public int getPackcode() {
		return this.packcode;
	}

	public void setPackcode(int packcode) {
		this.packcode = packcode;
	}

	@Column(name = "flowsize", nullable = false)
	public int getFlowsize() {
		return this.flowsize;
	}

	public void setFlowsize(int flowsize) {
		this.flowsize = flowsize;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "rate", nullable = false)
	public int getRate() {
		return this.rate;
	}

	public void setRate(int rate) {
		this.rate = rate;
	}

	@Column(name = "local", nullable = false)
	public int getLocal() {
		return this.local;
	}

	public void setLocal(int local) {
		this.local = local;
	}

	@Column(name = "operator", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "province", length = 45)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "des", length = 200)
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	@Column(name = "delflag", nullable = false)
	public int getDelflag() {
		return this.delflag;
	}

	public void setDelflag(int delflag) {
		this.delflag = delflag;
	}

	@Override
	public String toString() {
		return "Product [uid=" + uid + ", productid=" + productid + ", packcode=" + packcode + ", flowsize=" + flowsize
				+ ", price=" + price + ", rate=" + rate + ", local=" + local + ", operator=" + operator + ", province="
				+ province + ", des=" + des + ", delflag=" + delflag + "]";
	}
	
	
}
